import { Lang } from '../types';

const strings = {
  id: {
    appName: 'ConcertID',
    home: 'Beranda',
    wishlist: 'Wishlist',
    calendar: 'Kalender',
    more: 'Lainnya',
    newsletter: 'Newsletter',
    concertsSection: 'Semua Konser',
    hotSection: '🔥 Konser Hot',
    totalConcerts: 'Total Konser',
    confirmed: 'Confirmed',
    rumor: 'Rumor',
    filterAll: 'Semua',
    filterConfirmed: 'Confirmed',
    filterRumor: 'Rumor',
    filterKpop: 'K-Pop',
    filterPop: 'Pop',
    filterRock: 'Rock',
    filterJazz: 'Jazz',
    filterIndie: 'Indie',
    filterUpcoming: 'Upcoming',
    filterPast: 'Past',
    filterWishlist: 'Wishlist',
    sortDateAsc: 'Tanggal Terdekat',
    sortDateDesc: 'Tanggal Terjauh',
    sortPriceAsc: 'Harga Terendah',
    sortPriceDesc: 'Harga Tertinggi',
    sortNameAsc: 'Nama A-Z',
    sortLabel: 'Urutkan',
    searchPlaceholder: 'Cari artis, venue, kota...',
    noResult: 'Tidak ada konser ditemukan',
    noResultSub: 'Coba ubah filter atau kata kunci pencarian',
    addedToWishlist: 'Ditambahkan ke wishlist ❤️',
    removedFromWishlist: 'Dihapus dari wishlist',
    goingVote: 'Kamu akan hadir! 🎉',
    interestedVote: 'Kamu tertarik! ✨',
    voteCancelled: 'Vote dibatalkan',
    commentSent: 'Komentar terkirim! 💬',
    reviewSubmitted: 'Review terkirim! ⭐',
    beenThere: 'Sudah Hadir',
    markBeenThere: 'Tandai Sudah Hadir',
    beenThereAdded: 'Ditandai sudah hadir! 🎵',
    beenThereRemoved: 'Tanda sudah hadir dihapus',
    linkCopied: 'Link disalin! 📋',
    rumorWarning: '⚠️ Info ini masih rumor, belum ada pengumuman resmi.',
    priceLabel: 'Harga Tiket',
    venueLabel: 'Venue',
    dateLabel: 'Tanggal',
    timeLabel: 'Waktu',
    promotorLabel: 'Promotor',
    lineupLabel: 'Lineup',
    ticketCategories: 'Kategori Tiket',
    setlistActual: 'Setlist Aktual',
    setlistPrediction: 'Prediksi Setlist',
    setlistDisclaimer: '* Prediksi berdasarkan setlist tur terkini',
    discussion: 'Diskusi',
    reviewRating: 'Rating & Review',
    going: 'Going',
    interested: 'Interested',
    writeReview: 'Tulis Review',
    submitReview: 'Kirim Review',
    writeComment: 'Tulis komentar...',
    send: 'Kirim',
    reply: 'Balas',
    like: 'Suka',
    likes: 'suka',
    newsletterTitle: 'Dapatkan Update Konser',
    newsletterSub: 'Subscribe newsletter kami untuk info konser terbaru, tiket, dan promo eksklusif.',
    newsletterBtn: 'Subscribe Newsletter',
    newsletterPlaceholder: 'Email kamu...',
    feedbackTitle: 'Kirim Feedback',
    feedbackSub: 'Ada info yang salah? Saran fitur? Laporan bug? Beritahu kami!',
    aboutTitle: 'Tentang ConcertID',
    aboutDesc: 'ConcertID adalah platform informasi konser internasional di Indonesia. Kami mengumpulkan info dari berbagai sumber terpercaya untuk membantu kamu merencanakan konser impian.',
    confirmed_desc: '✅ Confirmed: Konser sudah diumumkan resmi oleh promotor.',
    rumor_desc: '🔮 Rumor: Info beredar di komunitas, belum ada pengumuman resmi.',
    past_desc: '⏰ Past: Konser sudah berlangsung.',
    footerCopy: '© 2026 ConcertID · list-concert-tour.web.id',
    buyTicket: 'Beli Tiket',
    buyTicketNow: 'Beli Tiket Sekarang',
    hotSubtitle: 'Jangan sampai ketinggalan!',
    addToCalendar: 'Tambah ke Kalender',
    share: 'Bagikan',
    shareVia: 'Bagikan via',
    copyLink: 'Salin Link',
    openWhatsApp: 'Kirim ke WhatsApp',
    openInstagram: 'Buka Instagram',
    nativeShare: 'Bagikan...',
    sources: 'Sumber',
    socialMedia: 'Media Sosial',
    noSetlist: 'Setlist belum tersedia',
    noComments: 'Belum ada komentar. Jadilah yang pertama!',
    noReviews: 'Belum ada review. Bagikan pengalamanmu!',
    reviewOnlyPast: 'Review hanya bisa ditulis untuk konser yang sudah berlangsung.',
    avgRating: 'Rating Rata-rata',
    yourRating: 'Rating kamu',
    yourReview: 'Ceritakan pengalamanmu...',
    name: 'Nama',
    email: 'Email',
    category: 'Kategori',
    message: 'Pesan',
    sendFeedback: 'Kirim Feedback',
    website: 'Website',
    venues: 'Venue di Jakarta',
    ticketPlatforms: 'Platform Tiket',
    darkMode: 'Mode Gelap',
    language: 'Bahasa',
    statusGuide: 'Panduan Status',
    exploreConcer: 'Jelajahi Konser',
    emptyWishlist: 'Wishlist kamu kosong',
    emptyWishlistSub: 'Tambahkan konser favorit dengan menekan ikon ❤️',
    calendarTitle: 'Kalender Konser',
    genreLabel: 'Genre',
    platformLabel: 'Platform Tiket',
    priceRangeLabel: 'Range Harga',
    openMaps: 'Buka Google Maps',
    spotifyPreview: 'Preview di Spotify',
    forumJualBeli: 'Forum Jual Beli Tiket',
    cariTemanNonton: 'Cari Teman Nonton',
    fotoDariFans: 'Foto dari Fans',
    forumDisabled: 'Forum ditutup (konser sudah selesai)',
    forumDisabledRumor: 'Forum ditutup (konser belum dikonfirmasi)',
    namaKamu: 'Nama kamu *',
    kategoriTiket: 'Kategori tiket (mis. VIP, CAT 1)',
    jumlah: 'Jumlah (maks. 4)',
    hargaPerTiket: 'Harga per tiket',
    kontakWA: 'Kontak (WA/IG/Twitter) *',
    catatan: 'Catatan tambahan...',
    jual: 'Jual',
    beli: 'Beli',
    postingListing: 'Posting Listing',
    belumAdaListing: 'Belum ada listing. Jadilah yang pertama!',
    cariTemanSubtitle: 'Koordinasi beli tiket bareng atau cari teman nonton',
    cariTemanPlaceholder: 'Ceritakan kebutuhanmu (mis. Cari 2 tiket VIP, mau duduk bareng)',
    postCariTeman: 'Post',
    belumAdaCariTeman: 'Belum ada yang cari teman nonton. Jadilah yang pertama! 🎉',
    uploadFoto: 'Upload Foto Fans',
    belumAdaFoto: 'Belum ada foto. Upload fotomu dari konser ini!',
    diskusiDisabled: 'Konser sudah selesai — form komentar ditutup.',
    lihatSpotify: 'Buka di Spotify',
  },
  en: {
    appName: 'ConcertID',
    home: 'Home',
    wishlist: 'Wishlist',
    calendar: 'Calendar',
    more: 'More',
    newsletter: 'Newsletter',
    concertsSection: 'All Concerts',
    hotSection: '🔥 Hot Concerts',
    totalConcerts: 'Total Concerts',
    confirmed: 'Confirmed',
    rumor: 'Rumor',
    filterAll: 'All',
    filterConfirmed: 'Confirmed',
    filterRumor: 'Rumor',
    filterKpop: 'K-Pop',
    filterPop: 'Pop',
    filterRock: 'Rock',
    filterJazz: 'Jazz',
    filterIndie: 'Indie',
    filterUpcoming: 'Upcoming',
    filterPast: 'Past',
    filterWishlist: 'Wishlist',
    sortDateAsc: 'Nearest Date',
    sortDateDesc: 'Furthest Date',
    sortPriceAsc: 'Lowest Price',
    sortPriceDesc: 'Highest Price',
    sortNameAsc: 'Name A-Z',
    sortLabel: 'Sort',
    searchPlaceholder: 'Search artist, venue, city...',
    noResult: 'No concerts found',
    noResultSub: 'Try changing filters or search keywords',
    addedToWishlist: 'Added to wishlist ❤️',
    removedFromWishlist: 'Removed from wishlist',
    goingVote: "You're going! 🎉",
    interestedVote: "You're interested! ✨",
    voteCancelled: 'Vote cancelled',
    commentSent: 'Comment sent! 💬',
    reviewSubmitted: 'Review submitted! ⭐',
    beenThere: 'Been There',
    markBeenThere: 'Mark as Been There',
    beenThereAdded: 'Marked as been there! 🎵',
    beenThereRemoved: 'Been there mark removed',
    linkCopied: 'Link copied! 📋',
    rumorWarning: '⚠️ This is still a rumor, no official announcement yet.',
    priceLabel: 'Ticket Price',
    venueLabel: 'Venue',
    dateLabel: 'Date',
    timeLabel: 'Time',
    promotorLabel: 'Promoter',
    lineupLabel: 'Lineup',
    ticketCategories: 'Ticket Categories',
    setlistActual: 'Actual Setlist',
    setlistPrediction: 'Predicted Setlist',
    setlistDisclaimer: '* Prediction based on recent tour setlists',
    discussion: 'Discussion',
    reviewRating: 'Rating & Reviews',
    going: 'Going',
    interested: 'Interested',
    writeReview: 'Write Review',
    submitReview: 'Submit Review',
    writeComment: 'Write a comment...',
    send: 'Send',
    reply: 'Reply',
    like: 'Like',
    likes: 'likes',
    newsletterTitle: 'Get Concert Updates',
    newsletterSub: 'Subscribe to our newsletter for the latest concert info, tickets, and exclusive promos.',
    newsletterBtn: 'Subscribe Newsletter',
    newsletterPlaceholder: 'Your email...',
    feedbackTitle: 'Send Feedback',
    feedbackSub: 'Wrong info? Feature request? Bug report? Let us know!',
    aboutTitle: 'About ConcertID',
    aboutDesc: 'ConcertID is an international concert information platform in Indonesia. We gather info from various trusted sources to help you plan your dream concert.',
    confirmed_desc: '✅ Confirmed: Concert officially announced by promoter.',
    rumor_desc: '🔮 Rumor: Circulating in the community, no official announcement yet.',
    past_desc: '⏰ Past: Concert has already taken place.',
    footerCopy: '© 2026 ConcertID · list-concert-tour.web.id',
    buyTicket: 'Buy Ticket',
    buyTicketNow: 'Buy Ticket Now',
    hotSubtitle: "Don't miss out!",
    addToCalendar: 'Add to Calendar',
    share: 'Share',
    shareVia: 'Share via',
    copyLink: 'Copy Link',
    openWhatsApp: 'Send to WhatsApp',
    openInstagram: 'Open Instagram',
    nativeShare: 'Share...',
    sources: 'Sources',
    socialMedia: 'Social Media',
    noSetlist: 'Setlist not available yet',
    noComments: 'No comments yet. Be the first!',
    noReviews: 'No reviews yet. Share your experience!',
    reviewOnlyPast: 'Reviews can only be written for past concerts.',
    avgRating: 'Average Rating',
    yourRating: 'Your rating',
    yourReview: 'Share your experience...',
    name: 'Name',
    email: 'Email',
    category: 'Category',
    message: 'Message',
    sendFeedback: 'Send Feedback',
    website: 'Website',
    venues: 'Venues in Jakarta',
    ticketPlatforms: 'Ticket Platforms',
    darkMode: 'Dark Mode',
    language: 'Language',
    statusGuide: 'Status Guide',
    exploreConcer: 'Explore Concerts',
    emptyWishlist: 'Your wishlist is empty',
    emptyWishlistSub: 'Add favorite concerts by tapping the ❤️ icon',
    calendarTitle: 'Concert Calendar',
    genreLabel: 'Genre',
    platformLabel: 'Ticket Platform',
    priceRangeLabel: 'Price Range',
    openMaps: 'Open Google Maps',
    spotifyPreview: 'Preview on Spotify',
    forumJualBeli: 'Ticket Buy/Sell Forum',
    cariTemanNonton: 'Find Concert Friends',
    fotoDariFans: 'Fan Photos',
    forumDisabled: 'Forum closed (concert has ended)',
    forumDisabledRumor: 'Forum closed (concert not confirmed)',
    namaKamu: 'Your name *',
    kategoriTiket: 'Ticket category (e.g. VIP, CAT 1)',
    jumlah: 'Qty (max 4)',
    hargaPerTiket: 'Price per ticket',
    kontakWA: 'Contact (WA/IG/Twitter) *',
    catatan: 'Additional notes...',
    jual: 'Sell',
    beli: 'Buy',
    postingListing: 'Post Listing',
    belumAdaListing: 'No listings yet. Be the first!',
    cariTemanSubtitle: 'Coordinate group ticket purchases or find concert buddies',
    cariTemanPlaceholder: 'Describe your need (e.g. Looking for 2 VIP tickets, want to sit together)',
    postCariTeman: 'Post',
    belumAdaCariTeman: 'No one is looking for concert friends yet. Be the first! 🎉',
    uploadFoto: 'Upload Fan Photo',
    belumAdaFoto: 'No photos yet. Upload your photo from this concert!',
    diskusiDisabled: 'Concert has ended — comment form closed.',
    lihatSpotify: 'Open on Spotify',
  },
} as const;

export type StringKey = keyof typeof strings['id'];
export { strings };
